server:
  error:
    include-stacktrace: on_param
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/escola?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
